### ISSUE TITLE
Global java element search slow when liferay-portal source is open

### ISSUE THREAD

**Issue by gamerson** [angelozerr/eclipse-wtp-xml-search#44]
Steps to reproduce

1. install eclipse-wtp-xml-search
2. install extension to xml-search like liferay-ide which contains many <toJava> references 
3. open liferay portal project from source
4. open some right like UserLocalService and then select the class and do a global project search "References > Workspace" 

This process takes a very long time in my test environment, over 1 minute.  And most of the time at least 50 seconds looks like the XMLReferencesJavaSearchParticpant is active.  I'm attaching a threaddump that shows the two active threads are related to xml search.  https://gist.github.com/gamerson/487e2b01e75c6b4082cc

**Comment by angelozerr** [comment]
It's an hard issue -(

At first XMLReferenceJavaSearchParticipant is used to retrieve Java Classes, Methods with Ctrl+Shift+G inside Java Editor.

For instance if you do Ctrl+Shift+G inside `MyPortlet` Java class, it will search XML files which declare MyPortlet inside :

```xml
<portlet-class>MyPortlet</portlet-class> .
```

So I think you should have the same problem if you do Ctrl+Shift+G on a Java class.

To speed up the search, you must try to search inside few files or few folder. For instance for portlet, you must search directly inside portlet.xml. This search scope is managed with a querySpecification liek you have done : 

```xml
<extension point="org.eclipse.wst.xml.search.core.querySpecifications">
   ...
        <querySpecification id="liferay.portletxml.querySpecification"
                            class="com.liferay.ide.xml.search.ui.descriptors.PortletQuerySpecification" />
...
</extension>

<reference validatorId="com.liferay.ide.xml.search.ui.portletDescriptorValidator">
                <from
                    path="/ns:portlet-app/ns:portlet/ns:portlet-class"
                    targetNodes="text()"
                    querySpecificationId="liferay.portletxml.querySpecification" />
               <toJava extends="javax.portlet.GenericPortlet" />
            </reference>
```
It seems that your https://github.com/liferay/liferay-ide/blob/master/tools/plugins/com.liferay.ide.xml.search.ui/src/com/liferay/ide/xml/search/ui/descriptors/PortletQuerySpecification.java search portlet.xml inside WEB-INF folder. To speed up the search PortletQuerySpcification#IResource getResource( Object selectedNode, IResource resource )  should returns directly portlet.xml IFile and not the WEB-INF folder.

Today the search for portlet-class is done inside the whole XML files inside WEB-INF folder. It should be done just for portlet.xml

Hope you will understand my explanation.

**Comment by gamerson** [comment]
That makes sense, thanks for the pointer, we can update that in our codebase.  However, that doesn't seem to be a factor in this slowness.  Because i tested it after modifiying those classes and it didn't ever get called.  

After doing a profile session and CPU sampling I noticed most of the CPU time is used when looking up contentTypes.  ANd in our project we have lots of different content Types for each of the registered querys.  

See this stacktrace, according to the profile this type of computation is taking a lot of time:

https://gist.github.com/gamerson/487e2b01e75c6b4082cc#file-xml-search-threaddump-txt-L147-L200

**Comment by angelozerr** [comment]
Ok could you try 2 tests please : 

 * 1) modify DOMUtils#getStructuredModelContentTypeId by hard coding the content type id, to check if the problem comes from looking up contentTypes.
 * if 1) is checked, reuse the original code of DOMUtils#getStructuredModelContentTypeId and uninstall Ivy. It seems that IvySettingsContentDescriber is every time called :  https://gist.github.com/gamerson/487e2b01e75c6b4082cc#file-xml-search-threaddump-txt-L234

**Comment by gamerson** [comment]
The problem does come from looking up content types.  But not from the ivy describer necessarily.  Its just that ivy is called a lot.  

There are nearly 1,500 xml files in the portal source.  And over 1 million lines of XML source code.  And the XMLReferenceJavaSearchParticipant is flushing its index cache before each new search run in the portal here:  https://github.com/angelozerr/eclipse-wtp-xml-search/blob/master/core/org.eclipse.wst.xml.search.editor/src/main/java/org/eclipse/wst/xml/search/editor/internal/jdt/search/XMLReferenceJavaSearchParticipant.java#L170

So that means that for each new search run in portal source it is going to have to reindex all 1500 xml files and that means 1500 new contentType lookups.  Those contentType individually are not that expensive but it adds up in this case.

So could the indexFiles not be flushed automatically?  But maybe a global resource listener could flush them when those files change?    Also many of the files can be 'assumed' to be the right content type if the content type filenames match.   So for all Sevice Builder content types in Liferay IDE we define that content type as being for files named service.xml.  Could we do this cheaper check instead of invoking a real content type check which causes the file to be parsed?

**Comment by gamerson** [comment]
@angelozerr after looking at this all day I don't see any way to highly optimze the searching through of that many xml files, like you say its a hard problem.  Essentially there is no shortcut to asking eclipse if one of those 1,500 xml files is "interesting" with respect to xml toJava references.  

So I'm going to propose a workaround, that we add a new API (in non breaking way) to xml search that lets xml toJava references specify if a particular target project is a valid xml ref tojava project.  

Then in Liferay IDE we can have a global "black-list" for projects that we don't want xml-search to index for "toJava" refernces.  And by defualt we can specify the liferay portal source itself (we have users reporting that LiferayIDE is too slow when portal source is open).  But this feature may be wanted by some developers and if so they can disable the blacklist setting to remove the portal source code.
